defaults: &defaults
  domain: 'localhost:3000'
  website_name: 'scrinium'
  smtp_settings:
    address: 'smtpcloud.sohu.com'
    port: 25
    domain: 'R6sJVHCZfkBvjKNXmwh9GyhgpTecaErX.sendcloud.org'
    user_name: 'tianlu1677_test_2Sep5d'
    display_name: 'scrinium@scrinium.cn'
    password: 'dcwSRsFFMavqrfjZ'
    authentication: 'login'
    enable_starttls_auto: true
  qiniu:
    access_key: 'IHhEVasL8n_ZWSTYmoKlyyrT7hJIBmrwt3fR4XiJ'
    secret_key: 'yW3h_ZLrwBasec8H3u0QGYR5xZ5Ci9vGsIIKewTF'
    default_bucket: 'scrinium'
    default_bucket_domain: '7xllma.com1.z0.glb.clouddn.com'
    image_bucket: 'scrinium'
    image_bucket_domain: '7xllma.com1.z0.glb.clouddn.com'
  redis_server_host: '127.0.0.1'
  redis_server_port: '6379'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  domain: 'www.scrinium.cn'
